// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/BookingPage.tsx": () => import("../components/mockups/BookingPage.tsx"),
  "./components/mockups/LandingPage.tsx": () => import("../components/mockups/LandingPage.tsx"),
  "./components/mockups/LuxuryApp.tsx": () => import("../components/mockups/LuxuryApp.tsx")
};
